services:
  apache:
    build: ./apache
    container_name: apache
    ports:
      - "80:80"
    volumes:
      - ./src:/usr/local/apache2/htdocs/src
      - ./public:/usr/local/apache2/htdocs/public
    depends_on:
      - php
  php:
    build: ./php
    container_name: php
    volumes:
      - ./src:/usr/local/apache2/htdocs/src
      - ./public:/usr/local/apache2/htdocs/public

  mariadb:
    image: mariadb:latest
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: nein
      MYSQL_DATABASE: myapp
      MYSQL_USER: user
      MYSQL_PASSWORD: test
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
  bind9:
    build: ./bind
    container_name: bind9
    ports:
      - "53:53/udp"
      - "53:53/tcp"

volumes:
  mariadb_data: