services:
  apache:
    build: ./apache
    container_name: apache
    ports:
      - "80:80"
    volumes:
      - ./src:/usr/local/apache2/htdocs/src
      - ./public:/usr/local/apache2/htdocs/public
    depends_on:
      - php
  php:
    build: ./php
    container_name: php
    volumes:
      - ./src:/usr/local/apache2/htdocs/src
      - ./public:/usr/local/apache2/htdocs/public

  mariadb:
    image: mariadb:latest
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: myapp
      MYSQL_USER: user
      MYSQL_PASSWORD: userpass
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql

volumes:
  mariadb_data: